# Generated by Django 4.0.4 on 2022-05-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0002_alter_telegram_accounts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_accounts',
            name='proxy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
