# Generated by Django 4.0.4 on 2022-05-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('telegramBot', '0003_alter_telegram_accounts_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsession',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
