# Generated by Django 4.0.4 on 2022-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(max_length=200)),
                ('type', models.CharField(default='user', max_length=200)),
                ('users_scrapper', models.CharField(default=True, max_length=100)),
                ('dm_to_group', models.CharField(default=True, max_length=100)),
                ('dm_to_user', models.CharField(default=True, max_length=100)),
                ('add_users_to_group', models.CharField(default=True, max_length=100)),
                ('autoscout_scrap', models.CharField(default=True, max_length=100)),
            ],
        ),
    ]
