# Generated by Django 4.0.4 on 2022-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperOutput_withNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('links', models.TextField()),
                ('Name', models.TextField()),
                ('Price', models.CharField(max_length=100)),
                ('Kilometers', models.CharField(max_length=100)),
                ('Date', models.TextField()),
                ('Power', models.TextField()),
                ('Image', models.TextField()),
                ('Number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapperOutput_withoutNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('links', models.TextField()),
                ('Name', models.TextField()),
                ('Price', models.TextField()),
                ('Kilometers', models.TextField()),
                ('Date', models.TextField()),
                ('Power', models.TextField()),
                ('Image', models.TextField()),
            ],
        ),
    ]
